# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "tucn-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = [
	"Fufezan Mihai <https://github.com/fufexan/>"
]
license = "MIT"
description = "Diploma thesis template for students of the Technical University of Cluj-Napoca, Faculty of Electronics, Telecommunications and Information Technology"
repository = "https://github.com/fufexan/tucn-thesis"
keywords = ["UTCN", "TUCN", "Technical", "thesis", "ETTI", "ETIT", "telecom"]
categories = ["thesis"]
disciplines = [
	"computer-science",
	"mathematics",
	"electronics",
	"computer-engineering"
]
compiler = "0.11.0"
exclude = [
	".github",
	"docs",
	"gallery",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
	"thumbnail.png",
	"example.pdf",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
