[conf]
default-lang = "en"

[lang.en]
thesis = "Diploma Thesis"
supervisor = "Supervisor"
performed-in-year = "Performed in the school year"
submission-note = "Submission note"
approved = "Approved"

declaration-title = "Statutory declaration"
# declaration-text = """
# I declare that I have authored this thesis independently, that I have not used \
# other than the declared sources and that I have explicitly marked all material \
# which has been quoted either literally or by content from the used sources.
# """
# declaration-ai-clause = """
# I also used the following generative AI tools [e.g. ChatGPT, Grammarly Go, \
# Midjourney] for the following purpose:
# """
location-date = "Location, Date"

chapter = "Chapter"
section = "Section"
# Should be in the opposite language (here, "ro")
abstract = "Rezumat în limba română"

figure = "Figure"
table = "Table"
listing = "Listing"
equation = "Equation"

contents = "Contents"
bibliography = "Bibliography"
list-of-figures = "List of Figures"
list-of-tables = "List of Tables"
list-of-listings = "List of Listings"
glossary = "Glossary"

[lang.ro]
thesis = "Lucrare de licență"
supervisor = "Coordonator"
performed-in-year = "Realizată în anul"
submission-note = "Nota"
approved = "Aprobat"

declaration-title = "Declarație pe proprie răspundere"
# declaration-text = """
# TODO
# """
location-date = "Locație, Dată"

chapter = "Capitolul"
section = "Secțiunea"
# Should be in the opposite language (here, "en")
abstract = "Abstract"

figure = "Figura"
table = "Tabelul"
listing = "Listarea"
equation = "Ecuația"

contents = "Cuprins"
bibliography = "Bibliografie"
list-of-figures = "Listă figuri"
list-of-tables = "Listă tabele"
list-of-listings = "Listă listări"
glossary = "Glosar"
